version: '2'
services:
  node_app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    
  
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - node_app
